format = """
[](bg:#E56615 fg:#E56615)\
$directory\
[](fg:#E56615 bg:#B1831A)\
$git_branch\
$git_status\
[](fg:#B1831A bg:#618C11)\
$kubernetes\
$nodejs\
$rust\
$python\
$java\
$scala\
[](fg:#618C11 bg:#6562AC)\
$time\
$battery\
[ ](fg:#6562AC)\
"""

command_timeout = 1000
scan_timeout = 100

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#E56615"
style_root = "bg:#E56615"
format = '[$user ]($style)'

[directory]
style = "bg:#E56615"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#B1831A"
format = '[[ $symbol $branch ](bg:#B1831A)]($style)'

#[git_status]
#style = "bg:#B1831A"
#format = '[[($all_status $ahead_behind )](bg:#B1831A)]($style)'

[git_status]
style = "bg:#B1831A"
format = '([\( $all_status$ahead_behind\)]($style))'
conflicted = "conflicted "
ahead = 'ahead\($count\) '
behind = ""
diverged = "diverged "
up_to_date = ""
untracked = ""
stashed = ""
modified = "modified "
staged = "staged "
renamed = "renamed "
deleted = "deleted "

[nodejs]
symbol = ""
style = "bg:#618C11"
version_format = "v${raw}"
format = '[[ $symbol ($version) ](bg:#618C11)]($style)'

[rust]
symbol = ""
style = "bg:#618C11"
version_format = "v${raw}"
format = '[[ $symbol ($version) ](bg:#618C11)]($style)'

[python]
# Only use the `python3` binary to get the version.
python_binary = "python3"
style = "bg:#618C11"
version_format = "v${raw}"
format = '[[ $symbol ($version) ](bg:#618C11)]($style)'

[java]
style = "bg:#618C11"
version_format = "v${raw}"
format = '[[ $symbol ($version) ](bg:#618C11)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6562AC"
format = '[[ ♥ $time ](bg:#6562AC)]($style)'

[[battery.display]]
threshold = 40
